ORG 0100H                   ;IP 

MOV AH, 0
MOV AL, 00H
INT 10H

IMPRIMIR MACRO MENSAJE      ;DECLARACION DE MACRO PARA IMPRIMIR MENSAJES
    MOV DX, OFFSET MENSAJE  ;DESPLEGAR MENSAJE
    MOV AH, 9
    INT 21H
ENDM                        ;TERMINAR MACRO
                           
LEER MACRO                  ;DECLARACION DE MACRO PARA LEER LOS DATOS
    MOV AH, 1               ;GUARDAR DATO
    INT 21H
ENDM 

SALTO MACRO                 ;DECLARACION DE MACRO PARA SALTO DE LINEA Y RETORNO DE CARRO
    MOV AH, 0EH             ;SALTO DE LINEA
    MOV AL, 10
    INT 10H

    MOV AH, 0EH
    MOV AL, 13              ;RETORNO DE CARRO
    INT 10H
ENDM  

LIMPIAR MACRO               ;DECLARACION DE MACRO PARA LIMPIAR ENTRADA
    XOR AL, AL              ;EJECUTAMOS LA OPERACION XOR EN CADA REGISTRO PARA LIMPIARLO
    XOR AH, AH
    XOR BL, BL
    XOR BH, BH
    XOR DL, DL
ENDM
                            ;DECLARACION DE MACRO PARA REALIZAR EL AND
ANDM MACRO                  
    AND BL, BH              ;REALIZAMOS LA OPERACION CON LOS DATOS PREVIAMENTE GUARDADOS EN BL Y BH

    MOV AH, 02H             ;MOVEMOS 02H A AH PARA IMPRIMIR EL CARACTER
    MOV DL, BL              ;MOVEMOS EL RESULTADO A DL 
    MOV AL, DL              ;MOVEMOS EL RESULTADO A AL PARA IMPRIMIRLO
    INT 21H
ENDM 

NOTM MACRO                  ;DECLARACION DE MACRO PARA REALIZAR EL NOT
    SUB BL, 30H             ;RESTAMOS 30H PARA QUITAR LO QUE AGREGA EL RECIBIR LA ENTRADA DE TECLADO
    NOT BL                  ;REALIZAMOS LA OPERACION CON EL DATO GUARDADO EN BL
    MOV AH, 02H             ;MOVEMOS 02H A AH PARA IMPRIMIR EL CARACTER
    MOV DL, BL              ;MOVEMOS EL RESULTADO A DL
    MOV AL, DL              ;MOVEMOS EL RESULTADO A AL PARA IMPRIMIRLO
    INT 21H
ENDM

NEGM MACRO                  ;DECLARACION DE MACRO PARA REALIZAR EL NEG
    SUB BL, 30H             ;RESTAMOS 30H PARA QUITAR LO QUE AGREGA EL RECIBIR LA ENTRADA DE TECLADO
    NEG BL                  ;REALIZAMOS LA OPERACION CON EL DATO GUARDADO EN BL
    MOV AH, 02H             ;MOVEMOS 02H A AH PARA IMPRIMIR EL CARACTER
    MOV DL, BL              ;MOVEMOS EL RESULTADO A DL
    MOV AL, DL              ;MOVEMOS EL RESULTADO A AL PARA IMPRIMIRLO
    INT 21H  
ENDM   

ORM MACRO                   ;DECLARACION DE MACRO PARA REALIZAR EL OR
    OR BL, BH               ;REALIZAMOS LA OPERACION CON LOS DATOS GUARDADOS EN BL Y BH

    MOV AH, 02H             ;MOVEMOS 02H A AH PARA IMPRIMIR EL CARACTER
    MOV DL, BL              ;MOVEMOS EL RESULTADO A DL
    MOV AL, DL              ;MOVEMOS EL RESULTADO A AL PARA IMPRIMIRLO
    INT 21H
ENDM 

XORM MACRO                  ;DECLARACION DE MACRO PARA REALIZAR EL OR
    XOR BL, BH              ;REALIZAMOS LA OPERACION CON LOS DATOS GUARDADOS EN BL Y BH

    MOV AH, 02H             ;MOVEMOS 02H A AH PARA IMPRIMIR EL CARACTER
    MOV DL, BL              ;MOVEMOS EL RESULTADO A DL
    MOV AL, DL              ;MOVEMOS EL RESULTADO A AL PARA IMPRIMIRLO
    INT 21H
ENDM 


;AND 
IMPRIMIR msjeAND
SALTO

IMPRIMIR msje               ;LLAMADO DE MACRO PARA EL PRIMER MENSAJE
LEER                        ;LLAMADO DE MACRO PARA GUARDAR EL PRIMER NUMERO

MOV BL, AL                  ;MOVER EL NUMERO A BL                  

SALTO 

IMPRIMIR msje2              ;LLAMADA DE MACRO PARA EL SEGUNDO MENSAJE
LEER 

MOV BH, AL                  ;MOVER EL SEGUNDO NUMERO A BH

SALTO                       ;LLAMADA DE MACRO PARA DAR SALTO DE LINEA Y RETORNO DE CARRO

IMPRIMIR msje3              ;(DEJARE DE COMENTAR LAS LINEAS QUE SEAN IGUALES)

ANDM                        ;LLAMADA DE MACRO PARA REALIZAR EL AND Y DAR RESULTADO      
SALTO
;NOT 
IMPRIMIR msjeNOT

LIMPIAR                     ;LLAMADA DE MACRO PARA LIMPIAR LOS REGISTROS                       

SALTO
                    
IMPRIMIR msje
LEER

MOV BL, AL

SALTO

IMPRIMIR msje3

NOTM                        ;LLAMADA DE MACRO PARA EL NOT Y DAR RESULTADO  
SALTO
;NEG
IMPRIMIR msjeNEG
LIMPIAR

SALTO

IMPRIMIR msje
LEER   

MOV BL, AL

SALTO

IMPRIMIR msje3

NEGM                        ;LLAMADA DE MACRO PARA EL NEG Y DAR RESULTADO      
SALTO
;OR
IMPRIMIR msjeOR
LIMPIAR

SALTO

IMPRIMIR msje
LEER

MOV BL, AL

SALTO 

IMPRIMIR msje2              
LEER 

MOV BH, AL                  

SALTO

IMPRIMIR msje3              

ORM                         ;LLAMADA DE MACRO PARA EL OR Y DAR RESULTADO
SALTO
;XOR 
IMPRIMIR msjeXOR
LIMPIAR
SALTO

IMPRIMIR msje
LEER

MOV BL, AL

SALTO 

IMPRIMIR msje2              
LEER 

MOV BH, AL                  

SALTO

IMPRIMIR msje3              

XORM                        ;LLAMADA DE MACRO PARA EL XOR Y DAR RESULTADO      


ret

msje db "Dame un numero: $"  
msje2 db "Dame otro numero: $"
msje3 db "Resultado: $" 
msjeAND db "OPERACION AND $"
msjeNOT db "OPERACION NOT $"
msjeNEG db "OPERACION NEG $"
msjeOR db "OPERACION OR $"
msjeXOR db "OPERACION XOR $"